### ISSUE TITLE
Private data indexes must copy to the correct folder during "release". K8S builder is not supporting the private data indexes.

### ISSUE THREAD

**Issue by davidfdr** [hyperledger-labs/fabric-builder-k8s#106]
It appears that the folders needed by the private data is not being copied during release:

https://github.com/hyperledger-labs/fabric-builder-k8s/blob/main/internal/util/copy.go#L16-L40

Private Data Indexes with private data:
https://hyperledger-fabric.readthedocs.io/en/latest/private_data_tutorial.html#using-indexes-with-private-data

**Comment by jt-nti** [comment]
Thanks for the defect! I'll add a test based on the [asset-transfer-private-data sample](https://github.com/hyperledger/fabric-samples/blob/main/asset-transfer-private-data/chaincode-go/META-INF/statedb/couchdb/collections/assetCollection/indexes/indexOwner.json) and get that working.

**Comment by jt-nti** [comment]
Fixed in #106
