### ISSUE TITLE
k8s owner reference is not set in CC child pod

### ISSUE THREAD

**Issue by jkneubuh** [hyperledger-labs/fabric-builder-k8s#88]
When the chaincode pod is created by the k8s builder, it does not currently set the pod `owner` attribute. 
https://kubernetes.io/docs/concepts/overview/working-with-objects/owners-dependents/

Update the owner reference for the child pod such that it is set as a dependent resource created by the peer.  This will force k8s to run an automatic GC of the chaincode pod if/when the peer is terminated.

Some original context and thread was discussed over on discord at [#fabric-kubernetes](https://discord.com/channels/905194001349627914/1072646153025376376), reported by @alius.miles

**Comment by tbondarchuk** [comment]
Example of project using standalone pods but with owner set: [cnpg](https://github.com/cloudnative-pg/cloudnative-pg/blob/main/pkg/utils/ownership.go#L26)

**Comment by jt-nti** [comment]
I think there are a couple of cases where an owner reference won't be possible:

- The peer, and therefore the k8s builder, doesn't always run in kubernetes
- If the `FABRIC_K8S_BUILDER_NAMESPACE` environment variable is set the chaincode pod could be in a different namespace to the peer:
    "A valid owner reference consists of the object name and a UID within the same namespace as the dependent object."

**Comment by Vikash-8090-Yadav** [comment]
Hey, @jt-nti @jkneubuh  I want to work on this. Can u please provide more information on what exactly the problem is?

**Comment by jt-nti** [comment]
Hi @Vikash-8090-Yadav, the background to this issue is in a Discord thread which is linked above, along with the Kubernetes doc on owners and dependents. This issue is to add the required configuration to the chaincode pod when possible, e.g. see the link Taras put in his comment. The builder would need to be running in Kubernetes, and in the same namespace, which I think it should be possible to check.

**Comment by solo-daemon** [comment]
Hi, I would like to work on this issue

**Comment by solo-daemon** [comment]
@jt-nti @jkneubuh I have added a pr which checks if a peer pod exist in the same namespace in which we are creating the chain pod it will set the peer pod as an owner. Is this the right approach ?

**Comment by jt-nti** [comment]
With #119, kubernetes now cleans up chaincode jobs/pods when the peer is terminated
