### ISSUE TITLE
Support private images

### ISSUE THREAD

**Issue by fernandobsb** [hyperledger-labs/fabric-builder-k8s#96]
Currently haven't found anything that supports private images. So when the chaincode pod is created it shows an error. It would be possible to implement support for private images using "imagePullSecrets" as a parameter so that we can inform the credential of the image's private repository.

**Comment by jt-nti** [comment]
Hi @fernandobsb, private images are supported using the `FABRIC_K8S_BUILDER_SERVICE_ACCOUNT` environment variable. This is definitely a common requirement so I think it needs documenting better but hopefully the [Add ImagePullSecrets to a service account](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#add-imagepullsecrets-to-a-service-account) k8s doc should help in the mean time. Let me know if you hit any problems. Thanks.

**Comment by fernandobsb** [comment]
Hi @jt-nti, thanks for the support. Closing this issue.
