### ISSUE TITLE
K8s-builder support fabric network multi arch amd64 and arm64?

### ISSUE THREAD

**Issue by fernandobsb** [hyperledger-labs/fabric-builder-k8s#97]
Hi everyone, I hope everyone is doing well. About the k8s-builder project I came across an important question regarding the arch that the environment was provisioned. In a scenario where we have 3 orgs with the following distribution Org1 was provisioned in an arch:AMD64 environment, Org2 also in an arch:AMD64 environment, while Org3 was provisioned in an arch:ARM64 environment. In this scenario using k8s-builder the digest of the chaincode image would be only 1. Since they are environments with different arch each image will have a different digest AMD64 images will have a digest while ARM64 images will have another digest purely because they are different architectures .
Knowing this difference an AMD64 image will not work in an ARM64 environment and vice versa, the version of k8s-builder currently does not support image parameter per arch, on this point is there any workaround for using k8s-builder in such a scenario Similar to the one mentioned above?
In our reviews we actually saw that this would have to be implemented for it to work correctly. So that all chaincode packages have the same ID when they are installed in any environment be it AMD64 or ARM64 or any other architecture.
Have you already checked something about and or is there any intention to support multiple architectures with this project, since FABRIC itself in its 2.5.x version started to support ARM images by default?

**Comment by jt-nti** [comment]
If you're using GitHub Actions to build chaincode images, the [GitHub Action to build and push Docker images with Buildx](https://github.com/docker/build-push-action) should help. For example,
https://github.com/hyperledger-labs/fabric-builder-k8s/blob/main/.github/workflows/docker-build.yml#L49
